In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [2]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [4]:
arr.astype(np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
arr.reshape(5,2)[2,1]

6

In [5]:
arr.reshape(5,2)[:2]

array([[1, 2],
       [3, 4]])

In [8]:
arr.sum()

55

In [11]:
arr.argmin()

0

In [12]:
arr.argmax()

9

In [13]:
arr.min()

1

In [14]:
arr.max()

10

In [15]:
arr.mean()

5.5

In [24]:
np.median(arr)

5.5

In [25]:
arr= np.arange(1,11)
arr1=[x+5 for x in arr]
arr2=[[arr],[arr1]]
arr2

[[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])],
 [[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]]]

In [8]:
array=[1,2,2,3,4,4]
uniq=np.unique(array)
uniq

array([1, 2, 3, 4])

In [9]:
array=[3,1,2]
sort=np.sort(array)
sort

array([1, 2, 3])

In [21]:
array1=[1,2]
array2=[3,4]
array=np.concatenate((array1,array2))
array

array([1, 2, 3, 4])

In [23]:
np.vstack((array1,array2))

array([[1, 2],
       [3, 4]])

In [24]:
np.transpose((array1,array2))

array([[1, 3],
       [2, 4]])

In [25]:
np.dot(array1,array2)

11

In [53]:
arr=np.random.rand(5)
arr

array([0.37704126, 0.69657723, 0.21760099, 0.85346239, 0.23490287])

In [56]:
np.random.randn(5)

array([-0.3068131 , -1.01476727,  0.74740992, -0.96368389,  0.57392125])

In [73]:
array=np.array([1,2,3,4,5,6])
reshape=array.reshape(2,3)
reshape

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
greater5=array >5
greater5
# mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])